In [1]:
from keras.models import Sequential
from keras.layers import Convolution2D , MaxPooling2D , Flatten, Dense
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.
C:\Users\master\anaconda3\envs\python-cvcourse\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\master\anaconda3\envs\python-cvcourse\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\master\anaconda3\envs\python-cvcourse\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\maste

In [2]:
train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

# this is the augmentation configuration we will use for testing:
# only rescaling
test_datagen = ImageDataGenerator(rescale=1./255)

# this is a generator that will read pictures found in
# subfolers of 'data/train', and indefinitely generate
# batches of augmented image data
training_set = train_datagen.flow_from_directory(
        'dataset/train',  # this is the target directory
        target_size=(64, 64),  # all images will be resized to 64 * 64
        batch_size=16,
        classes = ['beauty','fashion','home','nutrition','stationary'],
        class_mode='categorical'
        )

# this is a similar generator, for testing data
test_set = test_datagen.flow_from_directory(
        'dataset/test',
        target_size=(64, 64),
        batch_size=16,
        classes = ['beauty','fashion','home','nutrition','stationary'],
        class_mode='categorical'
        )

Found 779 images belonging to 5 classes.
Found 191 images belonging to 5 classes.


In [3]:
classifier=Sequential()

classifier.add(Convolution2D(16,3,3,input_shape=(64,64,3),activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))

classifier.add(Convolution2D(32,3,3,activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))

classifier.add(Convolution2D(64,3,3,activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))

classifier.add(Convolution2D(64,3,3,activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))

classifier.add(Flatten())

classifier.add(Dense(output_dim=128,activation='relu'))
classifier.add(Dense(output_dim=5,activation='softmax'))

classifier.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

C:\Users\master\anaconda3\envs\python-cvcourse\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3), input_shape=(64, 64, 3..., activation="relu")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\master\anaconda3\envs\python-cvcourse\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu")`
  
C:\Users\master\anaconda3\envs\python-cvcourse\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu")`
  if __name__ == '__main__':
C:\Users\master\anaconda3\envs\python-cvcourse\lib\site-packages\ipykernel_launcher.py:12: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu")`
  if sys.path[0] == '':
C:\Users\master\anaconda3\envs\python-cvcourse\lib\site-packages\ipykernel_lau

In [4]:
classifier.fit_generator(training_set,
                         samples_per_epoch = 779,
                         nb_epoch= 30,
                         validation_data = test_set,
                         nb_val_samples = 191,
                         verbose = 1
                        )

C:\Users\master\anaconda3\envs\python-cvcourse\lib\site-packages\ipykernel_launcher.py:6: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
  
C:\Users\master\anaconda3\envs\python-cvcourse\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras_pre..., validation_data=<keras_pre..., verbose=1, steps_per_epoch=48, epochs=30, validation_steps=191)`
  


Epoch 1/30
19/48 [==========>...................] - ETA: 5s - loss: 1.5799 - acc: 0.2632

C:\Users\master\anaconda3\envs\python-cvcourse\lib\site-packages\PIL\Image.py:931: UserWarning: Palette images with Transparency   expressed in bytes should be converted to RGBA images
  'to RGBA images')


48/48 [==============================] - 9s 180ms/step - loss: 1.5144 - acc: 0.3344 - val_loss: 1.3467 - val_acc: 0.4398
Epoch 2/30
48/48 [==============================] - 8s 161ms/step - loss: 1.3865 - acc: 0.4039 - val_loss: 1.2628 - val_acc: 0.4869
Epoch 3/30
48/48 [==============================] - 9s 184ms/step - loss: 1.3295 - acc: 0.4457 - val_loss: 1.2503 - val_acc: 0.5183
Epoch 4/30
48/48 [==============================] - 7s 150ms/step - loss: 1.2948 - acc: 0.5077 - val_loss: 1.2040 - val_acc: 0.4921
Epoch 5/30
48/48 [==============================] - 9s 194ms/step - loss: 1.1431 - acc: 0.5480 - val_loss: 1.0239 - val_acc: 0.5602
Epoch 6/30
48/48 [==============================] - 9s 178ms/step - loss: 0.9656 - acc: 0.5985 - val_loss: 1.0364 - val_acc: 0.5812
Epoch 7/30
48/48 [==============================] - 9s 185ms/step - loss: 0.9616 - acc: 0.6351 - val_loss: 1.0232 - val_acc: 0.6178
Epoch 8/30
48/48 [==============================] - 7s 139ms/step - loss: 0.8284 - acc:

In [5]:
import cv2
import tensorflow as tf
import numpy as np

In [22]:
img = cv2.imread('et.jpg')
resize = cv2.resize(img,(64,64))

In [23]:
yhat = classifier.predict(np.expand_dims(resize/255, 0))

In [24]:
yhat

array([[7.0340291e-05, 6.4426118e-01, 2.4390032e-03, 8.0354316e-03,
        3.4519404e-01]], dtype=float32)

In [25]:
if yhat.argmax() == 0:
    print('this image is a beauty product')
elif yhat.argmax() == 1:
    print('this image is a fashion product')
elif yhat.argmax() == 2:
    print('this image is a home product')
elif yhat.argmax() == 3:
    print('this image is a nutrition product')
elif yhat.argmax() == 4:
    print('this is Stationary product')
else:
    print('error undefined image')

this image is a fashion product


In [14]:
img2 = cv2.imread('testing2.jpg')
resize2 = cv2.resize(img2,(64,64))
yhat2 = classifier.predict(np.expand_dims(resize2/255, 0))
yhat2

array([[0.0131353 , 0.00375347, 0.00776086, 0.00196051, 0.9733899 ]],
      dtype=float32)

In [15]:
if yhat2.argmax() == 0:
    print('this image is a beauty product')
elif yhat2.argmax() == 1:
    print('this image is a fashion product')
elif yhat2.argmax() == 2:
    print('this image is a home product')
elif yhat2.argmax() == 3:
    print('this image is a nutrition product')
elif yhat2.argmax() == 4:
    print('this is Stationary product')
else:
    print('error undefined image')

this is Stationary product


In [16]:
img3 = cv2.imread('testing3.jpg')
resize3 = cv2.resize(img3,(64,64))
yhat3 = classifier.predict(np.expand_dims(resize3/255, 0))
yhat3

array([[8.5623473e-01, 1.2843159e-02, 3.1688850e-02, 2.6350326e-04,
        9.8969720e-02]], dtype=float32)

In [17]:
if yhat3.argmax() == 0:
    print('this image is a beauty product')
elif yhat3.argmax() == 1:
    print('this image is a fashion product')
elif yhat3.argmax() == 2:
    print('this image is a home product')
elif yhat3.argmax() == 3:
    print('this image is a nutrition product')
elif yhat3.argmax() == 4:
    print('this is Stationary product')
else:
    print('error undefined image')

this image is a beauty product


In [27]:
img4 = cv2.imread('neu.jpg')
resize4 = cv2.resize(img4,(64,64))
yhat4 = classifier.predict(np.expand_dims(resize4/255, 0))
yhat4

array([[7.0517686e-05, 4.3372076e-02, 3.4209323e-04, 9.3056637e-01,
        2.5649007e-02]], dtype=float32)

In [28]:
if yhat4.argmax() == 0:
    print('this image is a beauty product')
elif yhat4.argmax() == 1:
    print('this image is a fashion product')
elif yhat4.argmax() == 2:
    print('this image is a home product')
elif yhat4.argmax() == 3:
    print('this image is a nutrition product')
elif yhat4.argmax() == 4:
    print('this is Stationary product')
else:
    print('error undefined image')

this image is a nutrition product


In [26]:
classifier.save('model.h5')